from .LoadCheckpoint import NODE_CLASS_MAPPINGS as LOAD_CHECKPOINT_NODE_MAPPINGS
from .LoadCheckpoint import NODE_DISPLAY_NAME_MAPPINGS as LOAD_CHECKPOINT_DISPLAY_MAPPINGS
from .randomchoice import NODE_CLASS_MAPPINGS as RANDOM_CHOICE_NODE_MAPPINGS
from .randomchoice import NODE_DISPLAY_NAME_MAPPINGS as RANDOM_CHOICE_DISPLAY_MAPPINGS

NODE_CLASS_MAPPINGS = {
    **LOAD_CHECKPOINT_NODE_MAPPINGS,
    **RANDOM_CHOICE_NODE_MAPPINGS
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **LOAD_CHECKPOINT_DISPLAY_MAPPINGS,
    **RANDOM_CHOICE_DISPLAY_MAPPINGS
}

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']